# Generated by Django 2.2.12 on 2021-05-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=50)),
                ('number', models.IntegerField(default=None)),
                ('date', models.IntegerField(default=None)),
                ('details', models.CharField(max_length=50)),
            ],
        ),
    ]
