# Generated by Django 2.2.12 on 2021-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210626_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.IntegerField(default=None, help_text='Enter a valid date MMDD'),
        ),
    ]
