version: '3'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123pass
      - POSTGRES_DB=covid19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: ./mysite
      dockerfile: Dockerfile
    command: bash -c "wait-for-it db:5432 -- guvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./mysite/:/usr/src/mysite/
    environment:
      - DB_URL=postgresql://admin:123pass@db/covid19
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.http.config:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
      