# Generated by Django 2.2.12 on 2021-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='amka',
            field=models.IntegerField(default=None),
        ),
    ]
