# Generated by Django 2.2.12 on 2021-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20210626_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
